[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# can also override with the FOUNDRY_ETH_RPC_URL environment variable
eth_rpc_url='https://rpc.flashbots.net'
# eth_rpc_url='https://polygon-rpc.com'
